### ISSUE TITLE
Error: inputRange must be monotonically increasing 0,-32 at invariant

### ISSUE THREAD

**Issue by owenauch** [underscopeio/react-native-floating-hearts#3]
I was trying to use this library by passing a new, increased prop for count to this component every time that it increased. However, I keep getting this error: ` Error: inputRange must be monotonically increasing 0,-32 at invariant`.

When I log the prop value for count in the render method, it renders twice with the same count, which I think is the problem. Monotonically increasing would mean that it should never render with the same value or lower, only a larger one. So I'm not really sure how to fix this, because the render always runs twice in React, so the same props will be rendered twice.

**Comment by ignacioola** [comment]
Hey @owenauch, could you provide a minimal example and some steps to reproduce it? Thanks.

**Comment by AaronVasquez** [comment]
I don't think this is due to rendering the count. It's an animation error. The number on the right (-32) needs to be > 0. 

I'm guessing the problem is here:
https://github.com/underscopeio/react-native-floating-hearts/blob/master/FloatingHearts.js#L146

**Comment by owenauch** [comment]
Yes it is, I got it working. Thanks!

**Comment by tombaki** [comment]
@owenauch how did u solve this issues

**Comment by nppull** [comment]
@tombaki 
set height for parent view

```
<View style={{ width: 200, height: 200}}>
    <FloatingHearts count={count} />
</View>
```

**Comment by eramudeep** [comment]
still facing the same error
<img width="336" alt="Screenshot 2021-12-30 at 2 44 12 PM" src="https://user-images.githubusercontent.com/38516686/147738060-a705f588-758b-49fb-9607-217861202c64.png">

**Comment by chiragmakwana000** [comment]
I am having the issue with android, its working fine in ios.
can someone please help me to find solution ? @nppull  @AaronVasquez @tombaki @eramudeep
