### ISSUE TITLE
Problem Android

### ISSUE THREAD

**Issue by Angelk90** [underscopeio/react-native-floating-hearts#5]
I've tried the code post example, but on android not out of life.
It will not start.

**Comment by ignacioola** [comment]
Hey @Angelk90, I added a basic example here:

https://github.com/underscopeio/react-native-floating-hearts/tree/master/examples/basic

Try to run it and if it doesn't work please submit an issue following the issue template I just added to the project.

Thanks.

**Comment by Angelk90** [comment]
@ignacioola , @stevelacy : There are two problems:
1) It does not work on android, nothing happens I looked at the example too
2) prop-types must be changed with import PropTypes from 'prop-types';
